disabled_rules:
- identifier_name # There are 999+ errors for this rule
- force_cast # There 155 errors
- function_parameter_count # we have 2 errors, fix them implies a big refactor
- empty_count # There is an error for OrderedSet and now is not possible to fix it

opt_in_rules:
- empty_count
- empty_string

identifier_name:
    excluded: # excluded via string array
        - id

line_length:
    warning: 150
    error: 1450
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 6
    error: 8

excluded:
- Build
- Config
- Carthage
- fastlane
- Pods
- sonar-reports
- SwiftLint/Common/3rdPartyLib
- vendor
