# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def github_pods
  pod 'Alamofire', '5.4'
  pod 'MovieModule',  :git => 'git@github.com:chanthony1/moviemodule081021.git'
  #pod 'MovieModule',  :path => '/Users/cquicano/Repositories/moviemodule081021'
  pod 'SwiftLint'
end

target 'MoviesProd' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  github_pods

end

target 'MoviesMock' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  github_pods

end

target 'MoviesStaging' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  github_pods

end